{
 "title": "Apama Monitoring",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Input Stats",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sag_apama_correlator_queued_input_total",
     "legendFormat": "Events Queued Input"
    },
    {
     "expr": "irate(sag_apama_correlator_input_total[10m])",
     "legendFormat": "Events Received/sec"
    }
   ]
  },
  {
   "title": "Output Stats",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(sag_apama_correlator_output_total[10m])",
     "legendFormat": "Events sent / sec"
    },
    {
     "expr": "sag_apama_correlator_queued_output_total",
     "legendFormat": "Events Queued Send"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sag_apama_correlator_physical_memory_bytes",
     "legendFormat": "Physical Memory"
    },
    {
     "expr": "sag_apama_correlator_virtual_memory_bytes",
     "legendFormat": "Virtual Memory"
    }
   ]
  },
  {
   "title": "Correlator Objects",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sag_apama_correlator_contexts_total",
     "legendFormat": "Contexts"
    },
    {
     "expr": "sag_apama_correlator_monitor_instances_total",
     "legendFormat": "Monitor Instances"
    },
    {
     "expr": "sag_apama_correlator_listeners_total",
     "legendFormat": "Listeners"
    }
   ]
  }
 ]
}