{
 "title": "Application Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Number of Robots",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sag_apama_correlator_user_apamax_training_robotTotal"
    }
   ]
  },
  {
   "title": "Number of errors",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sag_apama_correlator_user_apamax_training_errorTotal"
    }
   ]
  },
  {
   "title": "Robot Temperatures",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sag_apama_correlator_user_apamax_training_temperature_1_1",
     "legendFormat": "Robot 1.1"
    },
    {
     "expr": "sag_apama_correlator_user_apamax_training_temperature_1_2",
     "legendFormat": "Robot 1.2"
    },
    {
     "expr": "sag_apama_correlator_user_apamax_training_temperature_2_1",
     "legendFormat": "Robot 2.1"
    },
    {
     "expr": "sag_apama_correlator_user_apamax_training_temperature_2_2",
     "legendFormat": "Robot 2.2"
    },
    {
     "expr": "sag_apama_correlator_user_apamax_training_temperature_3_1",
     "legendFormat": "Robot 3.1"
    },
    {
     "expr": "sag_apama_correlator_user_apamax_training_temperature_3_2",
     "legendFormat": "Robot 3.2"
    },
    {
     "expr": "sag_apama_correlator_user_apamax_training_temperature_4_1",
     "legendFormat": "Robot 4.1"
    },
    {
     "expr": "sag_apama_correlator_user_apamax_training_temperature_4_2",
     "legendFormat": "Robot 4.2"
    },
    {
     "expr": "sag_apama_correlator_user_apamax_training_temperature_5_1",
     "legendFormat": "Robot 5.1"
    },
    {
     "expr": "sag_apama_correlator_user_apamax_training_temperature_5_2",
     "legendFormat": "Robot 5.2"
    },
    {
     "expr": "sag_apama_correlator_user_apamax_training_temperature_6_1",
     "legendFormat": "Robot 6.1"
    },
    {
     "expr": "sag_apama_correlator_user_apamax_training_temperature_6_2",
     "legendFormat": "Robot 6.2"
    },
    {
     "expr": "sag_apama_correlator_user_apamax_training_temperature_7_1",
     "legendFormat": "Robot 7.1"
    },
    {
     "expr": "sag_apama_correlator_user_apamax_training_temperature_7_2",
     "legendFormat": "Robot 7.2"
    },
    {
     "expr": "sag_apama_correlator_user_apamax_training_temperature_8_1",
     "legendFormat": "Robot 8.1"
    },
    {
     "expr": "sag_apama_correlator_user_apamax_training_temperature_8_2",
     "legendFormat": "Robot 8.2"
    },
    {
     "expr": "sag_apama_correlator_user_apamax_training_temperature_9_1",
     "legendFormat": "Robot 9.1"
    },
    {
     "expr": "sag_apama_correlator_user_apamax_training_temperature_9_2",
     "legendFormat": "Robot 9.2"
    },
    {
     "expr": "sag_apama_correlator_user_apamax_training_temperature_10_1",
     "legendFormat": "Robot 10.1"
    },
    {
     "expr": "sag_apama_correlator_user_apamax_training_temperature_10_2",
     "legendFormat": "Robot 10.2"
    },
    {
     "expr": "sag_apama_correlator_user_apamax_training_temperature_11_1",
     "legendFormat": "Robot 11.1"
    },
    {
     "expr": "sag_apama_correlator_user_apamax_training_temperature_11_2",
     "legendFormat": "Robot 11.2"
    },
    {
     "expr": "sag_apama_correlator_user_apamax_training_temperature_12_1",
     "legendFormat": "Robot 12.1"
    },
    {
     "expr": "sag_apama_correlator_user_apamax_training_temperature_12_2",
     "legendFormat": "Robot 12.2"
    },
    {
     "expr": "sag_apama_correlator_user_apamax_training_temperature_13_1",
     "legendFormat": "Robot 13.1"
    },
    {
     "expr": "sag_apama_correlator_user_apamax_training_temperature_13_2",
     "legendFormat": "Robot 13.2"
    }
   ]
  },
  {
   "title": "Current temperatures",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "sag_apama_correlator_user_apamax_training_temperature_1_1",
     "legendFormat": "Robot 1.1"
    },
    {
     "expr": "sag_apama_correlator_user_apamax_training_temperature_1_2",
     "legendFormat": "Robot 1.2"
    },
    {
     "expr": "sag_apama_correlator_user_apamax_training_temperature_2_1",
     "legendFormat": "Robot 2.1"
    },
    {
     "expr": "sag_apama_correlator_user_apamax_training_temperature_2_2",
     "legendFormat": "Robot 2.2"
    },
    {
     "expr": "sag_apama_correlator_user_apamax_training_temperature_3_1",
     "legendFormat": "Robot 3.1"
    },
    {
     "expr": "sag_apama_correlator_user_apamax_training_temperature_3_2",
     "legendFormat": "Robot 3.2"
    },
    {
     "expr": "sag_apama_correlator_user_apamax_training_temperature_4_1",
     "legendFormat": "Robot 4.1"
    },
    {
     "expr": "sag_apama_correlator_user_apamax_training_temperature_4_2",
     "legendFormat": "Robot 4.2"
    },
    {
     "expr": "sag_apama_correlator_user_apamax_training_temperature_5_1",
     "legendFormat": "Robot 5.1"
    },
    {
     "expr": "sag_apama_correlator_user_apamax_training_temperature_5_2",
     "legendFormat": "Robot 5.2"
    },
    {
     "expr": "sag_apama_correlator_user_apamax_training_temperature_6_1",
     "legendFormat": "Robot 6.1"
    },
    {
     "expr": "sag_apama_correlator_user_apamax_training_temperature_6_2",
     "legendFormat": "Robot 6.2"
    },
    {
     "expr": "sag_apama_correlator_user_apamax_training_temperature_7_1",
     "legendFormat": "Robot 7.1"
    },
    {
     "expr": "sag_apama_correlator_user_apamax_training_temperature_7_2",
     "legendFormat": "Robot 7.2"
    },
    {
     "expr": "sag_apama_correlator_user_apamax_training_temperature_8_1",
     "legendFormat": "Robot 8.1"
    },
    {
     "expr": "sag_apama_correlator_user_apamax_training_temperature_8_2",
     "legendFormat": "Robot 8.2"
    },
    {
     "expr": "sag_apama_correlator_user_apamax_training_temperature_9_1",
     "legendFormat": "Robot 9.1"
    },
    {
     "expr": "sag_apama_correlator_user_apamax_training_temperature_9_2",
     "legendFormat": "Robot 9.2"
    },
    {
     "expr": "sag_apama_correlator_user_apamax_training_temperature_10_1",
     "legendFormat": "Robot 10.1"
    },
    {
     "expr": "sag_apama_correlator_user_apamax_training_temperature_10_2",
     "legendFormat": "Robot 10.2"
    },
    {
     "expr": "sag_apama_correlator_user_apamax_training_temperature_11_1",
     "legendFormat": "Robot 11.1"
    },
    {
     "expr": "sag_apama_correlator_user_apamax_training_temperature_11_2",
     "legendFormat": "Robot 11.2"
    },
    {
     "expr": "sag_apama_correlator_user_apamax_training_temperature_12_1",
     "legendFormat": "Robot 12.1"
    },
    {
     "expr": "sag_apama_correlator_user_apamax_training_temperature_12_2",
     "legendFormat": "Robot 12.2"
    },
    {
     "expr": "sag_apama_correlator_user_apamax_training_temperature_13_1",
     "legendFormat": "Robot 13.1"
    },
    {
     "expr": "sag_apama_correlator_user_apamax_training_temperature_13_2",
     "legendFormat": "Robot 13.2"
    }
   ]
  }
 ]
}